<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
        <AssemblyName>AIOHHF</AssemblyName>
        <Version>1.1.1</Version>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>11</LangVersion>
        <RootNamespace>AIOHHF</RootNamespace>
        <BepInExPluginGuid>com.lac.aiohhf</BepInExPluginGuid>
        <BepInPluginName>AIOHHF</BepInPluginName>

        <RestoreAdditionalProjectSources>
            https://api.nuget.org/v3/index.json;
            https://nuget.bepinex.dev/v3/index.json;
        </RestoreAdditionalProjectSources>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all"/>
        <PackageReference Include="BepInEx.Core" Version="5.4.21"/>
        <PackageReference Include="BepInEx.PluginInfoProps" Version="1.1.0"/>
        <PackageReference Include="UnityEngine.Modules" Version="2019.4.36" IncludeAssets="compile"/>
        <PackageReference Include="PolySharp" Version="1.15.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Subnautica.Nautilus" Version="1.0.0-pre.47" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    </ItemGroup>

    <PropertyGroup>
        <!--If trying to build this project, please make sure the correct directory to your Subnautica folder is listed below:-->
        <GameDir>Z:\SteamLibrary\steamapps\common\Subnautica</GameDir>
    </PropertyGroup>
    <!--Defines the PluginsDir property for use in the Post-Build event-->
    <PropertyGroup>
        <PluginsDir>$(GameDir)\BepInEx\plugins</PluginsDir>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="EasyCraft">
        <HintPath>$(PluginsDir)\..\uninstalled plugins\EasyCraft\EasyCraft.dll</HintPath>
      </Reference>
      <Reference Include="PrototypeSubMod">
        <HintPath>$(PluginsDir)\PrototypeSubMod\PrototypeSubMod.dll</HintPath>
      </Reference>
    </ItemGroup>
    
    
    <!--Post-Build event that automatically places your mods folder with the DLL and documentation into your plugins folder as defined in GameDir.targets-->
    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
        <MakeDir Directories="$(PluginsDir)/AIOHHF"/>
      <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(PluginsDir)/AIOHHF" />
        <Copy SourceFiles="$(TargetDir)$(TargetName).pdb" DestinationFolder="$(PluginsDir)/AIOHHF"/>
        <Copy SourceFiles="$(ProjectDir)English.json" DestinationFolder="$(PluginsDir)/AIOHHF/Localization"/>
    </Target>
    
    
    
    
</Project>